package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

/**
 * PacienteId generated by hbm2java
 */
public class PacienteId implements java.io.Serializable {

	private Integer idPaciente;
	private Integer idPessoa;

	public PacienteId() {
	}

	public PacienteId(Integer idPaciente, Integer idPessoa) {
		this.idPaciente = idPaciente;
		this.idPessoa = idPessoa;
	}

	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PacienteId))
			return false;
		PacienteId castOther = (PacienteId) other;

		return ((this.getIdPaciente() == castOther.getIdPaciente()) || (this.getIdPaciente() != null
				&& castOther.getIdPaciente() != null && this.getIdPaciente().equals(castOther.getIdPaciente())))
				&& ((this.getIdPessoa() == castOther.getIdPessoa()) || (this.getIdPessoa() != null
						&& castOther.getIdPessoa() != null && this.getIdPessoa().equals(castOther.getIdPessoa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPaciente() == null ? 0 : this.getIdPaciente().hashCode());
		result = 37 * result + (getIdPessoa() == null ? 0 : this.getIdPessoa().hashCode());
		return result;
	}

}
