package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa implements java.io.Serializable {

	private int idPessoa;
	private String primeiroNome;
	private String morada;
	private String ultimoNome;
	private String nomeDoMeio;
	private String nacionalidade;
	private Date dataCriacao;
	private Date dataAlteracao;
	private String sexo;
	private Date dataNascimento;
	private String nomeMeio;

	public Pessoa() {
	}

	public Pessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Pessoa(int idPessoa, String primeiroNome, String morada, String ultimoNome, String nomeDoMeio,
			String nacionalidade, Date dataCriacao, Date dataAlteracao, String sexo, Date dataNascimento,
			String nomeMeio) {
		this.idPessoa = idPessoa;
		this.primeiroNome = primeiroNome;
		this.morada = morada;
		this.ultimoNome = ultimoNome;
		this.nomeDoMeio = nomeDoMeio;
		this.nacionalidade = nacionalidade;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
		this.sexo = sexo;
		this.dataNascimento = dataNascimento;
		this.nomeMeio = nomeMeio;
	}

	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public String getPrimeiroNome() {
		return this.primeiroNome;
	}

	public void setPrimeiroNome(String primeiroNome) {
		this.primeiroNome = primeiroNome;
	}

	public String getMorada() {
		return this.morada;
	}

	public void setMorada(String morada) {
		this.morada = morada;
	}

	public String getUltimoNome() {
		return this.ultimoNome;
	}

	public void setUltimoNome(String ultimoNome) {
		this.ultimoNome = ultimoNome;
	}

	public String getNomeDoMeio() {
		return this.nomeDoMeio;
	}

	public void setNomeDoMeio(String nomeDoMeio) {
		this.nomeDoMeio = nomeDoMeio;
	}

	public String getNacionalidade() {
		return this.nacionalidade;
	}

	public void setNacionalidade(String nacionalidade) {
		this.nacionalidade = nacionalidade;
	}

	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getNomeMeio() {
		return this.nomeMeio;
	}

	public void setNomeMeio(String nomeMeio) {
		this.nomeMeio = nomeMeio;
	}

}
