package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

/**
 * 1aFaseIntensiva generated by hbm2java
 */
public class PrimeraFaseIntensiva implements java.io.Serializable {

	private PrimeraFaseIntensiva id;

	public PrimeraFaseIntensiva() {
	}

	public PrimeraFaseIntensiva(PrimeraFaseIntensiva id) {
		this.id = id;
	}

	public PrimeraFaseIntensiva getId() {
		return this.id;
	}

	public void setId(PrimeraFaseIntensiva id) {
		this.id = id;
	}

}
