package model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1


import java.util.Date;

/**
 * 1aFaseIntensivaTomaMedicamentoId generated by hbm2java
 */
public class 1aFaseIntensivaTomaMedicamentoId  implements java.io.Serializable {


     private Integer id1aFaseIntensivaTomaMedicamento;
     private Date dataTomaMedicamento;
     private Integer id1aFaseIntensiva;
     private Integer idPessoa;

    public 1aFaseIntensivaTomaMedicamentoId() {
    }

    public 1aFaseIntensivaTomaMedicamentoId(Integer id1aFaseIntensivaTomaMedicamento, Date dataTomaMedicamento, Integer id1aFaseIntensiva, Integer idPessoa) {
       this.id1aFaseIntensivaTomaMedicamento = id1aFaseIntensivaTomaMedicamento;
       this.dataTomaMedicamento = dataTomaMedicamento;
       this.id1aFaseIntensiva = id1aFaseIntensiva;
       this.idPessoa = idPessoa;
    }
   
    public Integer getId1aFaseIntensivaTomaMedicamento() {
        return this.id1aFaseIntensivaTomaMedicamento;
    }
    
    public void setId1aFaseIntensivaTomaMedicamento(Integer id1aFaseIntensivaTomaMedicamento) {
        this.id1aFaseIntensivaTomaMedicamento = id1aFaseIntensivaTomaMedicamento;
    }
    public Date getDataTomaMedicamento() {
        return this.dataTomaMedicamento;
    }
    
    public void setDataTomaMedicamento(Date dataTomaMedicamento) {
        this.dataTomaMedicamento = dataTomaMedicamento;
    }
    public Integer getId1aFaseIntensiva() {
        return this.id1aFaseIntensiva;
    }
    
    public void setId1aFaseIntensiva(Integer id1aFaseIntensiva) {
        this.id1aFaseIntensiva = id1aFaseIntensiva;
    }
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof 1aFaseIntensivaTomaMedicamentoId) ) return false;
		 1aFaseIntensivaTomaMedicamentoId castOther = ( 1aFaseIntensivaTomaMedicamentoId ) other; 
         
		 return ( (this.getId1aFaseIntensivaTomaMedicamento()==castOther.getId1aFaseIntensivaTomaMedicamento()) || ( this.getId1aFaseIntensivaTomaMedicamento()!=null && castOther.getId1aFaseIntensivaTomaMedicamento()!=null && this.getId1aFaseIntensivaTomaMedicamento().equals(castOther.getId1aFaseIntensivaTomaMedicamento()) ) )
 && ( (this.getDataTomaMedicamento()==castOther.getDataTomaMedicamento()) || ( this.getDataTomaMedicamento()!=null && castOther.getDataTomaMedicamento()!=null && this.getDataTomaMedicamento().equals(castOther.getDataTomaMedicamento()) ) )
 && ( (this.getId1aFaseIntensiva()==castOther.getId1aFaseIntensiva()) || ( this.getId1aFaseIntensiva()!=null && castOther.getId1aFaseIntensiva()!=null && this.getId1aFaseIntensiva().equals(castOther.getId1aFaseIntensiva()) ) )
 && ( (this.getIdPessoa()==castOther.getIdPessoa()) || ( this.getIdPessoa()!=null && castOther.getIdPessoa()!=null && this.getIdPessoa().equals(castOther.getIdPessoa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId1aFaseIntensivaTomaMedicamento() == null ? 0 : this.getId1aFaseIntensivaTomaMedicamento().hashCode() );
         result = 37 * result + ( getDataTomaMedicamento() == null ? 0 : this.getDataTomaMedicamento().hashCode() );
         result = 37 * result + ( getId1aFaseIntensiva() == null ? 0 : this.getId1aFaseIntensiva().hashCode() );
         result = 37 * result + ( getIdPessoa() == null ? 0 : this.getIdPessoa().hashCode() );
         return result;
   }   


}
