package model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1



/**
 * 1aFaseIntensivaTomaMedicamento generated by hbm2java
 */
public class 1aFaseIntensivaTomaMedicamento  implements java.io.Serializable {


     private 1aFaseIntensivaTomaMedicamentoId id;

    public 1aFaseIntensivaTomaMedicamento() {
    }

    public 1aFaseIntensivaTomaMedicamento(1aFaseIntensivaTomaMedicamentoId id) {
       this.id = id;
    }
   
    public 1aFaseIntensivaTomaMedicamentoId getId() {
        return this.id;
    }
    
    public void setId(1aFaseIntensivaTomaMedicamentoId id) {
        this.id = id;
    }




}
