package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1


import java.util.Date;

/**
 * PrimeraFaseIntensiva generated by hbm2java
 */
public class PrimeraFaseIntensivaId  implements java.io.Serializable {


     private Integer idPessoa;
     private Integer id1aFaseIntensiva;
     private Date data1aFaseIntensiva;

    public PrimeraFaseIntensivaId() {
    }

    public PrimeraFaseIntensivaId(Integer idPessoa, Integer id1aFaseIntensiva, Date data1aFaseIntensiva) {
       this.idPessoa = idPessoa;
       this.id1aFaseIntensiva = id1aFaseIntensiva;
       this.data1aFaseIntensiva = data1aFaseIntensiva;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Integer getId1aFaseIntensiva() {
        return this.id1aFaseIntensiva;
    }
    
    public void setId1aFaseIntensiva(Integer id1aFaseIntensiva) {
        this.id1aFaseIntensiva = id1aFaseIntensiva;
    }
    public Date getData1aFaseIntensiva() {
        return this.data1aFaseIntensiva;
    }
    
    public void setData1aFaseIntensiva(Date data1aFaseIntensiva) {
        this.data1aFaseIntensiva = data1aFaseIntensiva;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrimeraFaseIntensiva) ) return false;
		 PrimeraFaseIntensiva castOther = ( PrimeraFaseIntensiva ) other; 
         
		 return ( (this.getIdPessoa()==castOther.getIdPessoa()) || ( this.getIdPessoa()!=null && castOther.getIdPessoa()!=null && this.getIdPessoa().equals(castOther.getIdPessoa()) ) )
 && ( (this.getId1aFaseIntensiva()==castOther.getId1aFaseIntensiva()) || ( this.getId1aFaseIntensiva()!=null && castOther.getId1aFaseIntensiva()!=null && this.getId1aFaseIntensiva().equals(castOther.getId1aFaseIntensiva()) ) )
 && ( (this.getData1aFaseIntensiva()==castOther.getData1aFaseIntensiva()) || ( this.getData1aFaseIntensiva()!=null && castOther.getData1aFaseIntensiva()!=null && this.getData1aFaseIntensiva().equals(castOther.getData1aFaseIntensiva()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPessoa() == null ? 0 : this.getIdPessoa().hashCode() );
         result = 37 * result + ( getId1aFaseIntensiva() == null ? 0 : this.getId1aFaseIntensiva().hashCode() );
         result = 37 * result + ( getData1aFaseIntensiva() == null ? 0 : this.getData1aFaseIntensiva().hashCode() );
         return result;
   }   


}
