package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

/**
 * ProcessoInfecciologia generated by hbm2java
 */
public class ProcessoInfecciologia implements java.io.Serializable {

	private ProcessoInfecciologiaId id;

	public ProcessoInfecciologia() {
	}

	public ProcessoInfecciologia(ProcessoInfecciologiaId id) {
		this.id = id;
	}

	public ProcessoInfecciologiaId getId() {
		return this.id;
	}

	public void setId(ProcessoInfecciologiaId id) {
		this.id = id;
	}

}
