package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

/**
 * ProcessoInfecciologiaId generated by hbm2java
 */
public class ProcessoInfecciologiaId implements java.io.Serializable {

	private Integer idProcessoInfecciologia;
	private Integer idPessoa;
	private Integer idPaciente;
	private Integer idClassificacaoDoenca;
	private Integer idTipoDeDoente;
	private Integer idResultadoBk;

	public ProcessoInfecciologiaId() {
	}

	public ProcessoInfecciologiaId(Integer idProcessoInfecciologia, Integer idPessoa, Integer idPaciente,
			Integer idClassificacaoDoenca, Integer idTipoDeDoente, Integer idResultadoBk) {
		this.idProcessoInfecciologia = idProcessoInfecciologia;
		this.idPessoa = idPessoa;
		this.idPaciente = idPaciente;
		this.idClassificacaoDoenca = idClassificacaoDoenca;
		this.idTipoDeDoente = idTipoDeDoente;
		this.idResultadoBk = idResultadoBk;
	}

	public Integer getIdProcessoInfecciologia() {
		return this.idProcessoInfecciologia;
	}

	public void setIdProcessoInfecciologia(Integer idProcessoInfecciologia) {
		this.idProcessoInfecciologia = idProcessoInfecciologia;
	}

	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Integer getIdClassificacaoDoenca() {
		return this.idClassificacaoDoenca;
	}

	public void setIdClassificacaoDoenca(Integer idClassificacaoDoenca) {
		this.idClassificacaoDoenca = idClassificacaoDoenca;
	}

	public Integer getIdTipoDeDoente() {
		return this.idTipoDeDoente;
	}

	public void setIdTipoDeDoente(Integer idTipoDeDoente) {
		this.idTipoDeDoente = idTipoDeDoente;
	}

	public Integer getIdResultadoBk() {
		return this.idResultadoBk;
	}

	public void setIdResultadoBk(Integer idResultadoBk) {
		this.idResultadoBk = idResultadoBk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessoInfecciologiaId))
			return false;
		ProcessoInfecciologiaId castOther = (ProcessoInfecciologiaId) other;

		return ((this.getIdProcessoInfecciologia() == castOther.getIdProcessoInfecciologia())
				|| (this.getIdProcessoInfecciologia() != null && castOther.getIdProcessoInfecciologia() != null
						&& this.getIdProcessoInfecciologia().equals(castOther.getIdProcessoInfecciologia())))
				&& ((this.getIdPessoa() == castOther.getIdPessoa()) || (this.getIdPessoa() != null
						&& castOther.getIdPessoa() != null && this.getIdPessoa().equals(castOther.getIdPessoa())))
				&& ((this.getIdPaciente() == castOther.getIdPaciente()) || (this.getIdPaciente() != null
						&& castOther.getIdPaciente() != null && this.getIdPaciente().equals(castOther.getIdPaciente())))
				&& ((this.getIdClassificacaoDoenca() == castOther.getIdClassificacaoDoenca())
						|| (this.getIdClassificacaoDoenca() != null && castOther.getIdClassificacaoDoenca() != null
								&& this.getIdClassificacaoDoenca().equals(castOther.getIdClassificacaoDoenca())))
				&& ((this.getIdTipoDeDoente() == castOther.getIdTipoDeDoente())
						|| (this.getIdTipoDeDoente() != null && castOther.getIdTipoDeDoente() != null
								&& this.getIdTipoDeDoente().equals(castOther.getIdTipoDeDoente())))
				&& ((this.getIdResultadoBk() == castOther.getIdResultadoBk())
						|| (this.getIdResultadoBk() != null && castOther.getIdResultadoBk() != null
								&& this.getIdResultadoBk().equals(castOther.getIdResultadoBk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdProcessoInfecciologia() == null ? 0 : this.getIdProcessoInfecciologia().hashCode());
		result = 37 * result + (getIdPessoa() == null ? 0 : this.getIdPessoa().hashCode());
		result = 37 * result + (getIdPaciente() == null ? 0 : this.getIdPaciente().hashCode());
		result = 37 * result + (getIdClassificacaoDoenca() == null ? 0 : this.getIdClassificacaoDoenca().hashCode());
		result = 37 * result + (getIdTipoDeDoente() == null ? 0 : this.getIdTipoDeDoente().hashCode());
		result = 37 * result + (getIdResultadoBk() == null ? 0 : this.getIdResultadoBk().hashCode());
		return result;
	}

}
