package model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1



/**
 * 2aFaseContinuacao generated by hbm2java
 */
public class 2aFaseContinuacao  implements java.io.Serializable {


     private Integer idPessoa;

    public 2aFaseContinuacao() {
    }

    public 2aFaseContinuacao(Integer idPessoa) {
       this.idPessoa = idPessoa;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }




}
