package infecciologia.model;
// Generated 10/set/2016 13:22:45 by Hibernate Tools 5.1.0.Beta1

/**
 * TipoDoente generated by hbm2java
 */
public class TipoDoente implements java.io.Serializable {

	private int idTipoDoente;
	private String codigoTipoDoente;
	private String tipoDoente;

	public TipoDoente() {
	}

	public TipoDoente(int idTipoDoente) {
		this.idTipoDoente = idTipoDoente;
	}

	public TipoDoente(int idTipoDoente, String codigoTipoDoente, String tipoDoente) {
		this.idTipoDoente = idTipoDoente;
		this.codigoTipoDoente = codigoTipoDoente;
		this.tipoDoente = tipoDoente;
	}

	public int getIdTipoDoente() {
		return this.idTipoDoente;
	}

	public void setIdTipoDoente(int idTipoDoente) {
		this.idTipoDoente = idTipoDoente;
	}

	public String getCodigoTipoDoente() {
		return this.codigoTipoDoente;
	}

	public void setCodigoTipoDoente(String codigoTipoDoente) {
		this.codigoTipoDoente = codigoTipoDoente;
	}

	public String getTipoDoente() {
		return this.tipoDoente;
	}

	public void setTipoDoente(String tipoDoente) {
		this.tipoDoente = tipoDoente;
	}

}
