package ao.odp.hdp.infecciologia.model;
// Generated 10/set/2016 23:09:31 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassificacaoDoenca generated by hbm2java
 */
@Entity
@Table(name = "classificacao_doenca", schema = "public")
public class ClassificacaoDoenca implements java.io.Serializable {

	private int idClassificacaoDoenca;
	private String doenca;
	private String codigoDoenca;
	private Set<ProcessoInfecciologia> processoInfecciologias = new HashSet<ProcessoInfecciologia>(0);

	public ClassificacaoDoenca() {
	}

	public ClassificacaoDoenca(int idClassificacaoDoenca) {
		this.idClassificacaoDoenca = idClassificacaoDoenca;
	}

	public ClassificacaoDoenca(int idClassificacaoDoenca, String doenca, String codigoDoenca,
			Set<ProcessoInfecciologia> processoInfecciologias) {
		this.idClassificacaoDoenca = idClassificacaoDoenca;
		this.doenca = doenca;
		this.codigoDoenca = codigoDoenca;
		this.processoInfecciologias = processoInfecciologias;
	}

	@Id

	@Column(name = "id_classificacao_doenca", unique = true, nullable = false)
	public int getIdClassificacaoDoenca() {
		return this.idClassificacaoDoenca;
	}

	public void setIdClassificacaoDoenca(int idClassificacaoDoenca) {
		this.idClassificacaoDoenca = idClassificacaoDoenca;
	}

	@Column(name = "doenca")
	public String getDoenca() {
		return this.doenca;
	}

	public void setDoenca(String doenca) {
		this.doenca = doenca;
	}

	@Column(name = "codigo_doenca")
	public String getCodigoDoenca() {
		return this.codigoDoenca;
	}

	public void setCodigoDoenca(String codigoDoenca) {
		this.codigoDoenca = codigoDoenca;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classificacaoDoenca")
	public Set<ProcessoInfecciologia> getProcessoInfecciologias() {
		return this.processoInfecciologias;
	}

	public void setProcessoInfecciologias(Set<ProcessoInfecciologia> processoInfecciologias) {
		this.processoInfecciologias = processoInfecciologias;
	}

}
