package ao.odp.hdp.infecciologia.model;
// Generated 10/set/2016 23:09:31 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", schema = "public")
public class Pessoa implements java.io.Serializable {

	private int idPessoa;
	private String primeiroNome;
	private String morada;
	private String ultimoNome;
	private String nomeDoMeio;
	private String nacionalidade;
	private Date dataCriacao;
	private Date dataAlteracao;
	private String sexo;
	private Date dataNascimento;
	private String nomeMeio;
	private Set<Paciente> pacientes = new HashSet<Paciente>(0);

	public Pessoa() {
	}

	public Pessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Pessoa(int idPessoa, String primeiroNome, String morada, String ultimoNome, String nomeDoMeio,
			String nacionalidade, Date dataCriacao, Date dataAlteracao, String sexo, Date dataNascimento,
			String nomeMeio, Set<Paciente> pacientes) {
		this.idPessoa = idPessoa;
		this.primeiroNome = primeiroNome;
		this.morada = morada;
		this.ultimoNome = ultimoNome;
		this.nomeDoMeio = nomeDoMeio;
		this.nacionalidade = nacionalidade;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
		this.sexo = sexo;
		this.dataNascimento = dataNascimento;
		this.nomeMeio = nomeMeio;
		this.pacientes = pacientes;
	}

	@Id

	@Column(name = "id_pessoa", unique = true, nullable = false)
	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	@Column(name = "primeiro_nome")
	public String getPrimeiroNome() {
		return this.primeiroNome;
	}

	public void setPrimeiroNome(String primeiroNome) {
		this.primeiroNome = primeiroNome;
	}

	@Column(name = "morada")
	public String getMorada() {
		return this.morada;
	}

	public void setMorada(String morada) {
		this.morada = morada;
	}

	@Column(name = "ultimo_nome")
	public String getUltimoNome() {
		return this.ultimoNome;
	}

	public void setUltimoNome(String ultimoNome) {
		this.ultimoNome = ultimoNome;
	}

	@Column(name = "nome_do_meio")
	public String getNomeDoMeio() {
		return this.nomeDoMeio;
	}

	public void setNomeDoMeio(String nomeDoMeio) {
		this.nomeDoMeio = nomeDoMeio;
	}

	@Column(name = "nacionalidade")
	public String getNacionalidade() {
		return this.nacionalidade;
	}

	public void setNacionalidade(String nacionalidade) {
		this.nacionalidade = nacionalidade;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_criacao", length = 13)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_alteracao", length = 13)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Column(name = "sexo")
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 13)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "nome_meio")
	public String getNomeMeio() {
		return this.nomeMeio;
	}

	public void setNomeMeio(String nomeMeio) {
		this.nomeMeio = nomeMeio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Set<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
