package ao.odp.hdp.infecciologia.model;
// Generated 10/set/2016 23:09:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessoInfecciologia generated by hbm2java
 */
@Entity
@Table(name = "processo_infecciologia", schema = "public")
public class ProcessoInfecciologia implements java.io.Serializable {

	private int idProcessoInfecciologia;
	private ClassificacaoDoenca classificacaoDoenca;
	private Paciente paciente;
	private TipoDoente tipoDoente;
	private Integer idBk;
	private String numeroIdentificacao;
	private Integer idFase;
	private String processoInfecciologia;

	public ProcessoInfecciologia() {
	}

	public ProcessoInfecciologia(int idProcessoInfecciologia, String numeroIdentificacao) {
		this.idProcessoInfecciologia = idProcessoInfecciologia;
		this.numeroIdentificacao = numeroIdentificacao;
	}

	public ProcessoInfecciologia(int idProcessoInfecciologia, ClassificacaoDoenca classificacaoDoenca,
			Paciente paciente, TipoDoente tipoDoente, Integer idBk, String numeroIdentificacao, Integer idFase,
			String processoInfecciologia) {
		this.idProcessoInfecciologia = idProcessoInfecciologia;
		this.classificacaoDoenca = classificacaoDoenca;
		this.paciente = paciente;
		this.tipoDoente = tipoDoente;
		this.idBk = idBk;
		this.numeroIdentificacao = numeroIdentificacao;
		this.idFase = idFase;
		this.processoInfecciologia = processoInfecciologia;
	}

	@Id

	@Column(name = "id_processo_infecciologia", unique = true, nullable = false)
	public int getIdProcessoInfecciologia() {
		return this.idProcessoInfecciologia;
	}

	public void setIdProcessoInfecciologia(int idProcessoInfecciologia) {
		this.idProcessoInfecciologia = idProcessoInfecciologia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_classificacao_doenca")
	public ClassificacaoDoenca getClassificacaoDoenca() {
		return this.classificacaoDoenca;
	}

	public void setClassificacaoDoenca(ClassificacaoDoenca classificacaoDoenca) {
		this.classificacaoDoenca = classificacaoDoenca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paciente")
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_doente")
	public TipoDoente getTipoDoente() {
		return this.tipoDoente;
	}

	public void setTipoDoente(TipoDoente tipoDoente) {
		this.tipoDoente = tipoDoente;
	}

	@Column(name = "id_bk")
	public Integer getIdBk() {
		return this.idBk;
	}

	public void setIdBk(Integer idBk) {
		this.idBk = idBk;
	}

	@Column(name = "numero_identificacao", nullable = false)
	public String getNumeroIdentificacao() {
		return this.numeroIdentificacao;
	}

	public void setNumeroIdentificacao(String numeroIdentificacao) {
		this.numeroIdentificacao = numeroIdentificacao;
	}

	@Column(name = "id_fase")
	public Integer getIdFase() {
		return this.idFase;
	}

	public void setIdFase(Integer idFase) {
		this.idFase = idFase;
	}

	@Column(name = "processo_infecciologia")
	public String getProcessoInfecciologia() {
		return this.processoInfecciologia;
	}

	public void setProcessoInfecciologia(String processoInfecciologia) {
		this.processoInfecciologia = processoInfecciologia;
	}

}
